export const SET_PROJECTS = "SET_PROJECTS";

export const ADD_PROJECT = "ADD_PROJECT";

export const DELETE_PROJECT = "DELETE_PROJECT";

export const UPDATE_SND_LVL_MATRIX = "UPDATE_SND_LVL_MATRIX";

export const UPDATE_THRD_LVL_MATRIX = "UPDATE_THRD_LVL_MATRIX";

export const UPDATE_BLOCK_NAME = "UPDATE_BLOCK_NAME";
